import type { Product } from "@/types";

function p(
  id: string,
  name: string,
  emoji: string,
  category: Product["category"],
): Product {
  return { id, name, emoji, category };
}

/**
 * Default product catalog sourced from:
 * https://www.tubzbrands.co.uk/product-category/tubz-machines/tubz-tower/tubz-pots/
 * https://www.tubzbrands.co.uk/product-category/stickers/product-stickers/
 * https://www.tubzbrands.co.uk/product-category/toy-station-capsule-tower/
 *
 * IDs are stable slugs so they survive app resets without duplicate insertion.
 * Images are stored locally in assets/products/ — see constants/product-images.ts.
 */
export const DEFAULT_PRODUCTS: Product[] = [
  // ─── Sweets ────────────────────────────────────────────────────────────────
  p("tubz-skittles", "Skittles", "🌈", "sweet"),
  p("tubz-chupa-chups", "Chupa Chups", "🍭", "sweet"),
  p("tubz-maoam-mix", "Maoam Mix", "🍬", "sweet"),
  p("tubz-mini-sweet-mix", "Mini Sweet Mix", "🎀", "sweet"),
  p("tubz-gourmet-jelly-beans", "Gourmet Jelly Beans", "💎", "sweet"),
  p("tubz-hb-jelly-beans", "HB Jelly Beans", "🫘", "sweet"),
  p("tubz-hb-minimallows", "HB Minimallows", "☁️", "sweet"),
  p("tubz-jelly-sharks", "Jelly Sharks", "🦈", "sweet"),
  p("tubz-fizzy-watermelon", "Fizzy Watermelon", "🍉", "sweet"),
  p("tubz-fizzy-strawberry", "Fizzy Strawberry Pencils", "🍓", "sweet"),
  p("tubz-blue-raspberry", "Blue Raspberry Bon Bons", "🫐", "sweet"),
  p("tubz-mini-fizzy-cola", "Mini Fizzy Cola Bottles", "🥤", "sweet"),
  p("tubz-little-fizzy-mix", "Little Fizzy Mix", "💫", "sweet"),
  p("tubz-rainbow-belts", "Rainbow Belts", "🌈", "sweet"),
  p("tubz-rainbow-pencils", "Rainbow Assorted Pencils", "🖊️", "sweet"),
  p("tubz-tutti-frutti-bottles", "Tutti Frutti Bottles", "🍹", "sweet"),
  p("tubz-candy-crush-fizzy", "Candy Crush Fizzy Mix", "💫", "sweet"),
  p("tubz-candy-crush-jelly", "Candy Crush Jelly Mix", "🫙", "sweet"),
  p("tubz-candy-necklaces", "Candy Necklaces", "📿", "sweet"),
  p("tubz-candy-canes", "Candy Canes", "🍬", "sweet"),
  p("tubz-mini-eggs", "Mini Eggs", "🥚", "sweet"),
  p("tubz-mini-jelly-mix", "Mini Jelly Mix", "🍮", "sweet"),
  p("tubz-nice-kreem", "Nice Kreem", "🍦", "sweet"),
  p("tubz-mentos-fruits", "Mentos Fruits Assorted", "🍬", "sweet"),
  p("tubz-bubble-gum-bonbons", "Bubble Gum Bonbons", "🫧", "sweet"),
  p("strawberry-millions", "Strawberry Millions", "🍓", "sweet"),
  p("zoo-pops", "Zoo Pops", "🦁", "sweet"),
  p("juicy-drop-blasts", "Juicy Drop Blasts", "💥", "sweet"),
  p("gummy-burger-fries", "Gummy Burger and Fries", "🍔", "sweet"),
  p("tango-popping-candy", "Tango Popping Candy", "🍊", "sweet"),
  p("chocolate-jazzies", "Chocolate Jazzies", "🍫", "sweet"),
  p("white-choc-snowies", "White Chocolate Snowies", "❄️", "sweet"),
  p("chocolate-footballs", "Chocolate Footballs", "⚽", "sweet"),
  p("slush-puppie-chewbies", "Slush Puppie Chewbies", "🧊", "sweet"),
  p("slush-puppie-shock-rocks", "Slush Puppie Shock Rocks", "⚡", "sweet"),
  p("minions-stickers-candy", "Minions Stickers & Candy", "💛", "sweet"),
  p("pringles-original", "Pringles Original", "🥫", "sweet"),
  p("pringles-salt-vinegar", "Pringles Salt & Vinegar", "🥫", "sweet"),
  p("pringles-texas-bbq", "Pringles Texas BBQ", "🥫", "sweet"),
  p("pringles-paprika", "Pringles Paprika", "🥫", "sweet"),
  p("pringles-sour-cream", "Pringles Sour Cream", "🥫", "sweet"),

  // ─── Toys ──────────────────────────────────────────────────────────────────
  p("animal-fidget-poppers", "Animal Fidget Poppers", "🐾", "toy"),
  p("animal-races", "Animal Races", "🏁", "toy"),
  p("baby-meerkats", "Baby Meerkats", "🦦", "toy"),
  p("dino-sling-shots", "Dino Sling Shots", "🦕", "toy"),
  p("dinosaurs-4d-tattoos", "Dinosaurs 4D Tattoos", "🦖", "toy"),
  p("dreamworks-ar-discs", "DreamWorks AR Discs", "🎬", "toy"),
  p("extreme-putty", "Extreme Putty", "🫧", "toy"),
  p("fairys-and-friends", "Fairys & Friends", "🧚", "toy"),
  p("fantasy-4d-tattoos", "Fantasy 4D Tattoos", "🐉", "toy"),
  p("fidget-popper-balls", "Fidget Popper Balls", "🎯", "toy"),
  p("fidget-spinners", "Fidget Spinners", "🌀", "toy"),
  p("fidget-squishers", "Fidget Squishers", "💢", "toy"),
  p("frightnite-4d-tattoos", "FrightNite 4D Tattoos", "👻", "toy"),
  p("funky-fish", "Funky Fish", "🐠", "toy"),
  p("gonkers", "Gonkers", "🤡", "toy"),
  p("happy-hounds", "Happy Hounds", "🐕", "toy"),
  p("i-love-hedgehogs", "I Love Hedgehogs", "🦔", "toy"),
  p("i-love-puppies", "I Love Puppies", "🐶", "toy"),
  p("i-love-spring-bunnies", "I Love Spring Bunnies", "🐰", "toy"),
  p("lucky-dip-boys", "Lucky Dip Boys Toys Mix", "👦", "toy"),
  p("lucky-dip-girls", "Lucky Dip Girls Toys Mix", "👧", "toy"),
  p("lucky-duckies", "Lucky Duckies", "🦆", "toy"),
  p("magic-squishy-bead-balls", "Magic Squishy Bead Balls", "🫧", "toy"),
  p("moon-sand", "Moon Sand", "🌙", "toy"),
  p("pet-shoppe-4d-tattoos", "Pet Shoppe 4D Tattoos", "🐱", "toy"),
  p("puffle-pals", "Puffle Pals", "🫧", "toy"),
  p("rainbow-glitter-cord", "Rainbow Glitter Cord", "🌈", "toy"),
  p("roar-bots", "Roar-Bots", "🤖", "toy"),
  p("rough-rider-4d-tattoos", "Rough Rider 4D Tattoos", "🏍️", "toy"),
  p("skweeze-the-cheeze-2", "Skweeze The Cheeze! 2", "🧀", "toy"),
  p("slappy-bands", "Slappy Bands", "🪢", "toy"),
  p("slo-mo-do-zo", "Slo-Mo Do-Zo", "🐌", "toy"),
  p("slow-rise-capybara-2", "Slow Rise Capybara 2", "🦫", "toy"),
  p("sqwishland-city", "Sqwishland City", "🏙️", "toy"),
  p("sqwishland-farm", "Sqwishland Farm", "🐄", "toy"),
  p("sqwishland-forest", "Sqwishland Forest", "🌲", "toy"),
  p("sqwishland-jungle", "Sqwishland Jungle", "🌴", "toy"),
  p("sqwishland-polar", "Sqwishland Polar", "🐧", "toy"),
  p("sqwishland-sea", "Sqwishland Sea", "🌊", "toy"),
  p("sqwishland-swamp", "Sqwishland Swamp", "🐊", "toy"),
  p("star-monsters", "Star Monsters x 2", "⭐", "toy"),
  p("stretchy-pets", "Stretchy Pets", "🐾", "toy"),
  p("superthings-rescue-force", "SuperThings Rescue Force", "🦸", "toy"),
  p("topps-slam-attax", "Topps Slam Attax Trading Cards", "🃏", "toy"),
  p("trolls-puzzle-palz", "Trolls World Tour Puzzle Palz", "🎵", "toy"),
  p("tubz-electric-string", "Electric String", "⚡", "toy"),
  p("tubz-flashing-emoji-balls", "Flashing Emoji Balls", "😊", "toy"),
  p("tubz-flashing-monsters", "Flashing Monsters", "👾", "toy"),
  p("tubz-galaxy-bead-planet", "Galaxy Bead Planet", "🪐", "toy"),
  p("tubz-giant-globbers", "Giant Globbers", "🫧", "toy"),
  p("tubz-glitter-pets", "Glitter Pets", "✨", "toy"),
  p("tubz-mini-globbers", "Mini Globbers", "🫧", "toy"),
  p("tubz-mooneez", "Mooneez", "🌙", "toy"),
  p("tubz-squeeze-me-mix", "Squeeze Me Mix", "🤜", "toy"),
  p("tubz-splat-attack-mix", "Splat Attack Mix", "💥", "toy"),
  p("tubz-squishlets", "Squishlets", "🐛", "toy"),
  p("wakee-erasers-dinosaurs", "Wakee Erasers Dinosaurs", "🦕", "toy"),
  p("wakee-erasers-fun-fruits", "Wakee Erasers Fun Fruits", "🍎", "toy"),
  p("wakee-erasers-unicorns", "Wakee Erasers Unicorns", "🦄", "toy"),
  p("wakee-fast-food-erasers", "Wakee Fast Food Erasers", "🍕", "toy"),
  p("wakee-puzzler-erasers", "Wakee Puzzler Erasers", "🧩", "toy"),
  p("wakee-racers", "Wakee Racers", "🏎️", "toy"),
  p("wild-kingdom-4d-tattoos", "Wild Kingdom 4D Tattoos", "🐘", "toy"),
  p("wwe-slam-attax", "WWE Slam Attax Trading Cards", "🤼", "toy"),
  p("squishy-bead-pets-2", "Squishy Bead Pets 2", "🐾", "toy"),
  p("squishy-slo-rise-capybara", "Squishy Slo-Rise Capybara", "🦫", "toy"),
  p("squishy-slo-rise-wild", "Squishy Slo-Rise Wild Things", "🦁", "toy"),
  p("squishy-sparkly-muffin-pet", "Squishy Sparkly Muffin Pet", "🧁", "toy"),
  p("squishy-snax", "Squishy Snax", "🍟", "toy"),
];
