import type { ImageSourcePropType } from 'react-native';

/**
 * Static map of product ID → local asset.
 * All require() calls must be literal so Metro can resolve them at build time.
 */
export const PRODUCT_IMAGES: Record<string, ImageSourcePropType> = {
  // ─── Sweets ───────────────────────────────────────────────────────────────
  'tubz-skittles':            require('../assets/products/tubz-skittles.png'),
  'tubz-chupa-chups':         require('../assets/products/tubz-chupa-chups.png'),
  'tubz-maoam-mix':           require('../assets/products/tubz-maoam-mix.png'),
  'tubz-millions-mix':        require('../assets/products/tubz-millions-mix.jpg'),
  'tubz-mini-sweet-mix':      require('../assets/products/tubz-mini-sweet-mix.jpg'),
  'tubz-gourmet-jelly-beans': require('../assets/products/tubz-gourmet-jelly-beans.png'),
  'tubz-hb-jelly-beans':      require('../assets/products/tubz-hb-jelly-beans.png'),
  'tubz-hb-minimallows':      require('../assets/products/tubz-hb-minimallows.png'),
  'tubz-jelly-sharks':        require('../assets/products/tubz-jelly-sharks.png'),
  'tubz-fizzy-watermelon':    require('../assets/products/tubz-fizzy-watermelon.png'),
  'tubz-fizzy-strawberry':    require('../assets/products/tubz-fizzy-strawberry.png'),
  'tubz-blue-raspberry':      require('../assets/products/tubz-blue-raspberry.png'),
  'tubz-mini-fizzy-cola':     require('../assets/products/tubz-mini-fizzy-cola.png'),
  'tubz-little-fizzy-mix':    require('../assets/products/tubz-little-fizzy-mix.png'),
  'tubz-rainbow-belts':       require('../assets/products/tubz-rainbow-belts.png'),
  'tubz-rainbow-pencils':     require('../assets/products/tubz-rainbow-pencils.png'),
  'tubz-mini-tutti-frutti':   require('../assets/products/tubz-mini-tutti-frutti.jpg'),
  'tubz-candy-crush-tutti':   require('../assets/products/tubz-candy-crush-tutti.png'),
  'tubz-candy-necklaces':     require('../assets/products/tubz-candy-necklaces.png'),
  'tubz-candy-canes':         require('../assets/products/tubz-candy-canes.jpg'),
  'tubz-mini-eggs':           require('../assets/products/tubz-mini-eggs.png'),
  'tubz-nice-kreem':          require('../assets/products/tubz-nice-kreem.jpg'),
  'zoo-pops':                 require('../assets/products/zoo-pops.jpg'),
  'juicy-drop-blasts':        require('../assets/products/juicy-drop-blasts.jpg'),
  'gummy-burger-fries':       require('../assets/products/gummy-burger-fries.jpg'),
  'tango-popping-candy':      require('../assets/products/tango-popping-candy.jpg'),
  'chocolate-jazzies':        require('../assets/products/chocolate-jazzies.jpg'),
  'white-choc-snowies':       require('../assets/products/white-choc-snowies.jpg'),
  'slush-puppie-chewbies':    require('../assets/products/slush-puppie-chewbies.jpg'),
  'minions-stickers-candy':   require('../assets/products/minions-stickers-candy.jpg'),
  // ─── Toys ─────────────────────────────────────────────────────────────────
  'wakee-erasers-unicorns':   require('../assets/products/wakee-erasers-unicorns.jpg'),
  'wakee-erasers-dinosaurs':  require('../assets/products/wakee-erasers-dinosaurs.jpg'),
  'wakee-erasers-fun-fruits': require('../assets/products/wakee-erasers-fun-fruits.jpg'),
  'wakee-fast-food-erasers':  require('../assets/products/wakee-fast-food-erasers.jpg'),
  'wakee-puzzler-erasers':    require('../assets/products/wakee-puzzler-erasers.jpg'),
  'squishy-bead-pets-2':      require('../assets/products/squishy-bead-pets-2.jpg'),
  'fidget-spinners':          require('../assets/products/fidget-spinners.jpg'),
  'fidget-squishers':         require('../assets/products/fidget-squishers.jpg'),
  'tubz-giant-globbers':      require('../assets/products/tubz-giant-globbers.jpg'),
  'tubz-mini-globbers':       require('../assets/products/tubz-mini-globbers.jpg'),
  'tubz-squeeze-me-mix':      require('../assets/products/tubz-squeeze-me-mix.jpg'),
  'tubz-splat-attack-mix':    require('../assets/products/tubz-splat-attack-mix.jpg'),
  'tubz-squishlets':          require('../assets/products/tubz-squishlets.jpg'),
  'tubz-mooneez':             require('../assets/products/tubz-mooneez.jpg'),
  'tubz-galaxy-bead-planet':  require('../assets/products/tubz-galaxy-bead-planet.jpg'),
  'tubz-electric-string':     require('../assets/products/tubz-electric-string.png'),
  'tubz-flashing-monsters':   require('../assets/products/tubz-flashing-monsters.png'),
  'roar-bots':                require('../assets/products/roar-bots.jpg'),
  'gonkers':                  require('../assets/products/gonkers.jpg'),
  'i-love-puppies':           require('../assets/products/i-love-puppies.jpg'),
  'i-love-hedgehogs':         require('../assets/products/i-love-hedgehogs.jpg'),
  'frightnite-4d-tattoos':    require('../assets/products/frightnite-4d-tattoos.jpg'),
  'wild-kingdom-4d-tattoos':  require('../assets/products/wild-kingdom-4d-tattoos.png'),
  'rough-rider-4d-tattoos':   require('../assets/products/rough-rider-4d-tattoos.png'),
  'pet-shoppe-4d-tattoos':    require('../assets/products/pet-shoppe-4d-tattoos.png'),
  'fantasy-4d-tattoos':       require('../assets/products/fantasy-4d-tattoos.png'),
  'dinosaurs-4d-tattoos':     require('../assets/products/dinosaurs-4d-tattoos.png'),
  'superthings-rescue-force': require('../assets/products/superthings-rescue-force.jpg'),
  'star-monsters':            require('../assets/products/star-monsters.png'),
  'wwe-slam-attax':           require('../assets/products/wwe-slam-attax.jpg'),
  'topps-slam-attax':         require('../assets/products/topps-slam-attax.png'),
  'dreamworks-ar-discs':      require('../assets/products/dreamworks-ar-discs.png'),
  'fairys-and-friends':       require('../assets/products/fairys-and-friends.jpg'),
  'lucky-dip-girls':          require('../assets/products/lucky-dip-girls.jpg'),
  'lucky-dip-boys':           require('../assets/products/lucky-dip-boys.jpg'),
  'sqwishland-farm':          require('../assets/products/sqwishland-farm.png'),
  'sqwishland-polar':         require('../assets/products/sqwishland-polar.png'),
  'sqwishland-city':          require('../assets/products/sqwishland-city.png'),
};
